### ISSUE TITLE
ctrl-0

### ISSUE THREAD

**Issue by xiaoshui05** [futantan/atom#8]
我的atom使用这个快捷键没有反应，请问你碰到过吗？(系统：window10 x64   版本:1.16.0 x64)
![image](https://cloud.githubusercontent.com/assets/11335012/25381682/4ad47ef4-29e7-11e7-9adb-1a0d1a191741.png)

**Comment by futantan** [comment]
抱歉，没有遇到过，我用的是 macOS 的系统，你可以检查看看是否因为与其他应用快捷键冲突了，或者是因为安装的插件快捷键有冲突。
